### ISSUE TITLE
Add to inventory option on Snap It

### ISSUE THREAD

**Issue by EzequielDM** [WFCD/WFinfo#169] opened 2021-04-18 17:13 UTC
**Is your feature request related to a problem? Please describe.**
It's not exatcly an issue but managing inventory is kinda hard on Warframe considering we can't use the API to get a player's inventory, so having an app to control it is nice.

**Describe the solution you'd like**
Having the option to scan your own inventory of primed parts using snap it and having the option to add each one to your inventory inside the app, but don't make it automatic as sometimes it gets the name of the item wrong and it could mess everything up.
Either add a button below it (not ideal considering the boxes are very small) or add the function to Right Click a box to add one of that item to your inventory.

First issue would be having time to read everything carefully so you don't add the wrong items to your inventory, it would require the user to be fast or to raise the duration of the boxes, both are bad solutions as having the boxes for longer would affect every box, including relic drops info, which would be annoying.
Two solutions, either make a separate button for that or, a better option and easier to implement, make it so whenever you right click (or click the add to inv button, w/e you choose to do) the boxes don't disappear and you have a cross inside a square (or w/e you want to represent a close button) on the top right corner for when you're done.

This would make it easier to use the inventory function as I just don't use it because it would take some time to organize everything.

**Comment by dapal-003** [comment] 2021-04-18 18:31
Duplicate of https://github.com/WFCD/WFinfo/issues/66

Currently it's on indefinite hold due to some limitations:
Snap-it can not interpret numbers, this was deliberate chosen in order to remove false positives with characters like i/l >1 and o > 0

Any string shorter than 2 characters will be dropped to reduce false positives, many of the false positive scans are only one character long, and not a single prime item in the game has a one character long name.  

Item quantity is not necessary for the program to find a reward, due to how snap-it works, the image processing is relative and only that what the user scans. This is done to speed up performance of the already rather slow scanning. This can cause issues with item quantities becoming out of sync

**Closed by dapal-003** 2021-04-18 18:31 UTC

**Comment by EzequielDM** [comment] 2021-04-18 19:38
As stated inside my suggestion it'd only add one of that item to your inventory, which ultimately skips the need for the program to find the amount, letting the user right click as many times as they want would be more than enough, generally you won't have more than 10 of an item anyways.
Also, do consider that the amount of an item is displayed in a different position always at the same offset from one another, making a grid system is not that hard and it would allow for the OCR to only check the bounding boxes of those specific coordinates that would have the needed info instead of reading the entire screen, that, however, would require this feature to be separate from the snap it function and also would require the user to not use the scrolling bar and just the scroll wheel as that would affect the offsets.
